### ISSUE TITLE
Visual Studio 2019, x64 Native Tools Command Prompt for VS 2019, cake.bat, build fail: 3 errors

### ISSUE THREAD

**Issue by vasslavich** [lewissbaker/cppcoro#161]
c:\devzone\cppcoro>cake.bat
Traceback (most recent call last):
  File "c:\devzone\cppcoro\tools\cake\src\run.py", line 17, in <module>
    cake.main.execute()
  File "c:\devzone\cppcoro\tools\cake\src\cake\main.py", line 22, in execute
    import cake.runner
  File "c:\devzone\cppcoro\tools\cake\src\cake\runner.py", line 25
    from cake.async import flatten
              ^
SyntaxError: invalid syntax

**Comment by vasslavich** [comment]
Sorry, forgot: Python 3.8.3

**Comment by tavi-cacina** [comment]
As a workaround you may use: `vcpkg install cppcoro`

**Comment by pvthuyet** [comment]
Build failed vs2019  
```
D:\work\cppcoro>cake.bat
python: can't open file 'D:\work\cppcoro\tools\cake\src\run.py': [Errno 2] No such file or directory
```

**Comment by bullestock** [comment]
Or simply use a fork with CMake support: https://github.com/Garcia6l20/cppcoro
