### ISSUE TITLE
Failed to build on my Windows box

### ISSUE THREAD

**Issue by rodrigovaras** [lewissbaker/cppcoro#215]
Followed the instructions and get the following error:
D:\github\cppcoro>cake.bat release=debug architecture=x64 lib/build.cake
Traceback (most recent call last):
  File "D:\github\cppcoro\tools\cake\src\run.py", line 17, in <module>
    cake.main.execute()
  File "D:\github\cppcoro\tools\cake\src\cake\main.py", line 22, in execute
    import cake.runner
  File "D:\github\cppcoro\tools\cake\src\cake\runner.py", line 144
    def new_os_open(filename, flag, mode=0777):
                                         ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

python --version
Python 3.11.1

Anything missing ?

**Comment by donno** [comment]
The bundled version of Cake is written for Python 2, where Python 3 support is meant to come during the build process of the Cake package (i.e when the setup.py is built) which runs 2to3 over the code base.

As its being pulled in merely as a sub-module it means its expecting Python 2.7 is used.

For Windows, you may wish to use the vcpkg instead, which will in turn use CMake (and it has its own CMakeLists.txt).
